// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header.vue')['default']
    BallPopItem: typeof import('./src/components/ball-pop-item.vue')['default']
    BannerItem: typeof import('./src/components/banner-item.vue')['default']
    CardsContainer: typeof import('./src/components/cards-container.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FooterItem: typeof import('./src/components/footer-item.vue')['default']
    IndexBusiness: typeof import('./src/components/index-business.vue')['default']
    IndexCover: typeof import('./src/components/index-cover.vue')['default']
    IndexDaohe: typeof import('./src/components/index-daohe.vue')['default']
    IndexScene: typeof import('./src/components/index-scene.vue')['default']
    InnerTopItem: typeof import('./src/components/inner-top-item.vue')['default']
    LeftCard: typeof import('./src/components/left-card.vue')['default']
    RightCard: typeof import('./src/components/right-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
